export const GET_COCKTAIL_LIST = 'GET_COCKTAIL_LIST'
export const GET_COCKTAIL_LIST_LOADING = 'GET_COCKTAIL_LIST_LOADING';
export const GET_COCKTAIL_LIST_ASYNC = 'GET_COCKTAIL_LIST_ASYNC'
export const GET_COCKTAIL_LIST_ERROR = 'GET_COCKTAIL_LIST_ERROR'